# Generated by Django 4.0.6 on 2022-07-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='address', help_text='Not Required. Designates address of the user.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='city', help_text='Not Required. Designates city of residence.', max_length=100),
            preserve_default=False,
        ),
    ]
